# Site settings
title: AndrewLowther
email: andrew.l.lowther@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tech Lead at Made Media.
  Fairly good at lifting up heavy things and putting them down again
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrew.lowther.name" # the base hostname & protocol for your site
twitter_username: AndrewLowther
github_username:  AndrewLowther

# Build settings
markdown: kramdown
